# Generated by Django 3.0.3 on 2020-03-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('company', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell')], max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
