# Generated by Django 3.0.3 on 2020-03-04 16:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocksbackend', '0004_auto_20200303_0413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Portfolio',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='profile',
            new_name='portfolio',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='profile',
            new_name='portfolio',
        ),
    ]
